TestEncryptionApplication/Models/PersonneModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestEncryptionApplication.ServiceReference1;

namespace TestEncryptionApplication.Models
{
    public class PersonneModel
    {
        static Service1Client db = new Service1Client();

        /// <summary>
        /// Fonction permettant d'ajouter les informations d'une personne
        /// </summary>
        /// <param name="nom"></param>
        /// <param name="prenom"></param>
        /// <param name="dateNaissance"></param>
        /// <returns></returns>
        public static int AddPersonne(string nom, string prenom, DateTime dateNaissance)
        {
            return db.AddPersonne(nom, prenom, dateNaissance);
        }

        /// <summary>
        /// Fonction retourant la liste des personnes par nom
        /// </summary>
        /// <param name="nom"></param>
        /// <returns></returns>
        public static List<Personne> GetAllPersonnesByNom(string nom)
        {
            return db.GetPersonneByName(nom);
        }

        /// <summary>
        /// Fonction retourant la liste de toutes les personnes
        /// </summary>
        /// <returns></returns>
        public static List<Personne> GetPersonnes()
        {
            return db.GetPersonnes();
        }

        /// <summary>
        /// Fonction retournant une personne par son id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static Personne GetPersonneById(int id)
        {
            return db.GetPersonneById(id);
        }
    }
}

TestEncryptionApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestEncryptionApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TestEncryptionApplication/Controllers/PersonneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestEncryptionApplication.Models;
using TestEncryptionApplication.ServiceReference1;

namespace TestEncryptionApplication.Controllers
{
    public class PersonneController : Controller
    {
        /// <summary>
        /// Liste des personnes ajoutées
        /// </summary>
        /// <returns></returns>
        public ActionResult PersonnePage()
        {
            List<Personne> personnes = PersonneModel.GetPersonnes();

            return View(personnes);
        }

        /// <summary>
        /// Recherche sur une personne
        /// </summary>
        /// <param name="recherche"></param>
        /// <returns></returns>
        public ActionResult PersonneFilterPage(string recherche = null)
        {
            List<Personne> personnes = new List<Personne>();

            //Si recherche
            if (!String.IsNullOrEmpty(recherche))
            {
                personnes = PersonneModel.GetAllPersonnesByNom(recherche);
            }
            else{
                personnes = PersonneModel.GetPersonnes();
            }

            return View("~/Views/Personne/PersonnePage.cshtml",  personnes);
        }

        /// <summary>
        /// Page de création d'une personne
        /// </summary>
        /// <returns></returns>
        public ActionResult CreationPersonne()
        {
            return View(new Personne());
        }

        /// <summary>
        /// Envoie du formulaire depuis la page de création
        /// </summary>
        /// <param name="personne"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreationPersonneForm(Personne personne)
        {
            int resultat = PersonneModel.AddPersonne(personne.nom, personne.prenom, personne.date_naissance);

            return RedirectToAction("PersonnePage");
        }
    }
}

TestEncryptionApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TestEncryptionApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestEncryptionApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

TestEncryptionApplication/Views/Personne/CreationPersonne.cshtml
@using TestEncryptionApplication.ServiceReference1
@model Personne

@{
    ViewBag.Title = "CreationPersonne";
}

<h2>Création d'une personne</h2>

@using (Html.BeginForm("CreationPersonneForm", "Personne", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="prenom">Prénom</label>
        @Html.TextBoxFor(model => model.prenom, new { @class = "form-control", @id = "prenom", @placeholder = "Prenom", @type = "text", @required = "required" })
    </div>

    <div class="form-group">
        <label for="nom">Nom</label>
        @Html.TextBoxFor(model => model.nom, new { @class = "form-control", @id = "nom", @placeholder = "Nom", @type = "text", @required = "required" })
    </div>

    <div class="form-group">
        <label for="date-naissance">Date de naissance</label>
        @Html.TextBoxFor(model => model.date_naissance, String.Format("{0:dd/MM/yyyy}", Model.date_naissance), new { @class = "form-control", @type = "date", @id = "date-naissance", @placeholder = "Commentaire" })
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-info">Ajouter une personne</button>
    </div>
}

TestEncryptionApplication/Views/Personne/PersonnePage.cshtml
@using TestEncryptionApplication.ServiceReference1
@model List<Personne>


@{
    ViewBag.Title = "PersonnePage";
}

<div class="div-btn-add text-right">
    @Html.ActionLink("Ajouter une personne", "CreationPersonne", "Personne", new { }, new { @class = "btn btn-primary" })
</div>

@using (Html.BeginForm("PersonneFilterPage", "Personne", FormMethod.Post))
{
    <div class="form-group tex">
        <label for="recherche">Recherche par nom</label>
        <input type="search" placeholder="Recherche" id="recherche" name="recherche" class="form-control" />
    </div>

    <div class="text-center">
        <input type="submit" value="Rechercher" id="recherche" class="btn btn-success" />
    </div>
}

<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Prenom</th>
            <th>Nom</th>
            <th>Date de naissance</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id_personne</td>
                <td>@item.prenom</td>
                <td>@item.nom</td>
                <td>@item.date_naissance.ToShortDateString()</td>
            </tr>
        }
    </tbody>
</table>

TestEncryptionApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test encryption", "PersonnePage", "Personne", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>L'équipe AXOCARE</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>